### ISSUE TITLE
How to train with sample image

### ISSUE THREAD

**Issue by cspnanda** [isering/WoodPixel#1]
Very interesting work. Can you please add some instructions on how to run the sample code in finishNet folder and run the train.py

**Comment by isering** [comment]
Hi. In order to train the network: `python train.py --config <config_path> --model <output_path>`. A sample config.yaml file is in the config directory. Please not though that this is only used for Figure 19 in the paper. The wood puzzle generation is done using the C++ code. Please let me know if you run into any more issues.
